<?php
/*
Group 13
November 9, 2016
WEBD3201
The listing cities page
*/
$title = "Listing Cities";
$date = "November 9, 2016";
$filename = "listing-cities.php";
$description = "The Listing cities page";
include("header.php");
?>
<?php
$cities_table = 'cities';

$city = (isset($_COOKIE[$cities_table]))?$_COOKIE[$cities_table]:0;	
if (isset($_GET['city']))
{
	$dumValid = $_GET['city'];
}	
if($_SERVER["REQUEST_METHOD"] == "GET")
{
	
	//default mode when the page loads the first time
	//can be used to make decisions and initialize variables
	//ROW 2
	$minimum = "";
	$maximum = "";	
}
else if($_SERVER["REQUEST_METHOD"] == "POST")
{

	if (isset($_POST[$cities_table]))
	{
		$city = sumCheckBox($_POST[$cities_table]);
		setcookie($cities_table, $city, time()+ COOKIE_LENGTH, "/");
	}
	else
	{
		$city = 0;
		setcookie($cities_table, $city, time()+ COOKIE_LENGTH, "/");
	}
	
	
	$_SESSION['city'] = $city;
	
	//echo $_SESSION['city'];
	
	header("Location: listing-search.php");
}
	
?>
<script type="text/javascript">
<!--
	/*NOTE: for the following function to work, on your page
			you have to create a checkbox id'ed as city_toggle
				
	<input type="checkbox"  onclick="toggle(this);" name="city[]" value="0">
			
		and each city checkbox element has to be an named as an 
		array (specifically named "city[]")
		e.g.
			<input type="checkbox" name="city[]" value="1">Ajax
	*/
	function toggle(source) {
		checkboxes = document.getElementsByName('cities[]');
		for(i = 0; i < checkboxes.length; i++)
		{
			checkboxes[i].checked = source.checked;
		}
	}
		
//-->
</script>

<br/>
<form action="<?php echo $_SERVER['PHP_SELF'];  ?>" method="post">
<table>
	<tr>
		<td align="left">
		<?php 
		
			//SELECT ALL OPTIONS			
			echo "\n<input type=\"checkbox\"  onclick=\"toggle(this);\" name=\"".$cities_table."[]\" value=\"0\" /> Select All<br/>";					
			echo build_checkbox($cities_table, $city); 
		?>
		</td>
		<td>

		<!-- Image Map Generated by http://www.image-map.net/ -->
		<img src="images/imagemap.jpg" alt="DURHAM REGION MAP" usemap="#image-map" />

		<map name="image-map" id="image-map" >
		    <area  alt="Pickering" title="Pickering" href="./listing-search.php?submit=Search+source+code&amp;city=16" coords="13,205,188,205,188,297,114,296,107,301,103,309,108,315,112,319,99,347,101,359,104,367,114,377,118,385,114,401,104,406,94,404,79,388,71,381,63,383,54,397,52,401,33,400,24,393,14,382,10,372,8,351,7,330" shape="poly" />
		    <area  alt="Ajax" title="Ajax" href="./listing-search.php?submit=Search+source+code&amp;city=1" coords="112,310,112,306,148,305,188,306,188,402,125,402,125,377,113,363,109,354,109,345,117,336,120,326,121,318,119,312" shape="poly" />
		    <area  alt="Brooklin" title="Brooklin" href="./listing-search.php?submit=Search+source+code&amp;city=2" coords="197,275,286,207" shape="rect" />
		    <area  alt="Oshawa" title="Oshawa" href="./listing-search.php?submit=Search+source+code&amp;city=8" coords="349,402,364,401,371,404,377,404,379,401,380,322,380,206,295,208,295,344,294,383,294,396,294,401,290,403,290,405,300,407,310,404,320,404,333,403" shape="poly" />
		    <area  alt="Whitby" title="Whitby" href="./listing-search.php?submit=Search+source+code&amp;city=64" coords="198,282,286,282,286,394,274,400,264,398,255,394,241,386,228,389,213,394,207,394,198,394,198,342" shape="poly" />
		    <area  alt="Bowmanville" title="Bowmanville" href="./listing-search.php?submit=Search+source+code&amp;city=4" coords="642,237,755,236,755,429,752,442,738,444,706,442,676,439,658,438,640,430,623,425,604,423,586,420,567,416,551,411,533,409,503,418,495,423,476,425,460,422,445,415,429,414,403,411,388,405,388,213,565,213,564,237" shape="poly" />
		    <area  alt="Port Perry" title="Port Perry" href="./listing-search.php?submit=Search+source+code&amp;city=32" coords="388,203,565,203,559,63,425,127,420,124,462,60,467,40,462,34,455,31,439,33,420,39,404,55,392,74,382,99,379,102,377,96,379,30,382,17,380,12,361,12,197,12,195,195,192,199,261,199,388,199" shape="poly" />
		</map>
		
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<br/>
			<input style="align: center" type="submit" name="submit" value="Submit" />
			<br/>
		</td>
	</tr>
</table>

</form>

<?php include 'footer.php'; ?>